### PR TITLE
Ruby 2.4 - constant ::Fixnum is deprecated

### PR DESCRIPTION
**Pull request by rgioia**
Support without deprecation to Ruby 2.4

### CODE REVIEW

**Comment by acrogenesis** [comment]
👍

**Comment by radar** [comment]
Thanks @rgioia :heart: I will merge this in with #80, which should end up as 3.0.0. Just waiting on the Travis build.

**Comment by rgioia** [comment]
That's all right. Very nice! @radar

**Comment by radar** [comment]
3.0.0 has been released and includes this change. Please upgrade :) thanks for submitting a PR.

**Pull request closed without merging**
